<body>
    <!-- <?php var_dump($_POST); ?>
    <br>
    <?php var_dump($_FILES); ?> -->
    <section class="section">
        <div class="container">
            <div class="box">
                <div class="content">
                    <h2>Inserting status : <?php echo $status ?></h2>
                    <h3>Example from tags table</h3>
                    <div class="table">
                        <table>
                            <thead>
                                <tr>
                                    <th>categoryname</th>
                                    <th>code</th>
                                    <th>tag name</th>
                                    <th>tag description</th>
                                    <th>scheme name</th>
                                    <th>tagid</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                while ($row = $result->fetch(PDO::FETCH_ASSOC)) {
                                    if(!isset($schemename)){
                                        $schemename = $row['schemename'];
                                    }
                                    echo "<tr>";
                                    foreach ($row as $key => $value) {
                                        echo "<td>".$value."</td>";
                                    }
                                    echo "</tr>";
                                }
                                 ?>
                            </tbody>
                        </table>
                    </div>

                </div>
                <div class="columns has-text-centered">
                    <div class="column">
                        <a href="scheme" class="button">Cancel</a>
                    </div>
                    <div class="column">

                        <a href="scheme/comfirm/<?php echo $schemename ?>" class="button is-success">Confirm</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
