<body>
    <section class="section">
        <div class="container">
            <div class="box">
                <div class="content">
                    <h3>Sampling Method :</h3>
                </div>
                <div class="columns">
                    <div class="column">

                    </div>
                    <div class="column">
                        <div class="form">
                            <form class="" action="/scheme/confirm" method="post">
                                <!-- schemename -->
                                <div class="field">
                                    <label class="label">Scheme Name : </label>
                                    <div class="control">
                                        <input type="text" value="<?php echo $schemename; ?>" class="input" disabled>
                                        <input type="hidden" name="schemename" value="<?php echo $schemename; ?>">

                                    </div>
                                </div>
                                <!-- totaltags -->
                                <div class="field">
                                    <label class="label">Total Tags : </label>
                                    <div class="control">
                                        <input type="text" value="<?php echo $rowcount; ?>" class="input" disabled>
                                        <input type="hidden" name="rowcount" value="<?php echo $rowcount; ?>">
                                    </div>
                                </div>

                                <hr>

                                <div class="field">
                                    <label class="label">Link to MasterDB : </label>
                                        <div class="select">
                                            <select name="masterdbid">
                                                <?php
                                                    foreach ($masterdbs as $key => $value) {
                                                        echo "<option value='".$value[2]."'>$value[0] - $value[1] rows</option>";
                                                    }
                                                 ?>
                                            </select>
                                        </div>
                                </div>

                                <div class="field">
                                    <label class="label">% Sampling</label>
                                    <div class="control">
                                        <input type="text" name="percent" class="input" id="percent" onchange="checkSubmitStatus()">
                                    </div>
                                </div>
                                <hr>
                                <div class="columns">
                                    <div class="column has-text-centered">
                                        <a href="/" class="button">Cancel</a>
                                    </div>
                                    <div class="column">
                                        <div class="field">
                                            <div class="control has-text-centered">
                                                <input type="submit" name="" value="Create Scheme" class="button" id="submitbutton" disabled>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                                <div class="content">
                                    <h4>
                                        <span id="warningtext" class="is-danger"></span>
                                    </h4>
                                </div>

                            </form>
                        </div>
                    </div>
                    <div class="column">

                    </div>
                </div>

            </div>
        </div>
    </section>

    <script>
        function checkSubmitStatus(){
            var myButton = document.getElementById("submitbutton");
            var percent = document.getElementById("percent");
            var warningtext = document.getElementById("warningtext");

            if (percent.value > 100 || percent < 0) {
                myButton.disabled = true;
                warningtext.innerHTML = "Value of percentage should be between 1 -> 99";
            }else{
                myButton.disabled = false;
                warningtext.innerHTML = "";
            }
        }
    </script>
</body>
