<body>
    <section class="section">
        <div class="container">
            <div class="box">
                <div class="content">
                    <h3>Please Review</h3>
                    <div class="table">
                        <table>
                            <thead>
                                <tr>
                                    <th>categoryname</th>
                                    <th>code</th>
                                    <th>tag name</th>
                                    <th>tag description</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                while ($row = $rows->fetch(PDO::FETCH_ASSOC)) {
                                    echo "<tr>";
                                    foreach ($row as $key => $value) {
                                        echo "<td>".$value."</td>";
                                    }
                                    echo "</tr>";
                                }
                                 ?>
                            </tbody>
                        </table>
                    </div>

                </div>
                <div class="columns has-text-centered">
                    <div class="column">
                        <a href="/" class="button">Cancel</a>
                    </div>
                    <div class="column">

                        <a href="/scheme/setup/<?php echo $_POST['schemename'] ;?>" class="button is-success">Confirm</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
