
<body>
    <section class="section">
        <div class="container">
            <div class="box">
                <div class="content">
                    <h2>Done Creating New Scheme</h2>
                    <h4>Scheme Name : <?php echo $result['schemename'] ?></h4>
                    <h4>Timestamp: <?php echo $result['timestamp']; ?></h4>
                    <div class="has-text-centered">
                        <h4>Click the button below to go home</h4>
                        <a href="/" class="button is-link">Go Home</a>
                    </div>
                </div>

            </div>
        </div>
    </section>
</body>
