<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title><?=$title ?></title>
        <link rel="stylesheet" href="/css/bulma.min.css">
        <link rel="stylesheet" href="/css/my.css">
        <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
    </head>

    <body>
        <nav class="navbar" role="navigation" aria-label="main navigation">
          <div class="navbar-menu">
              <div class="navbar-end">
                  <?php if (isset($_SESSION['scheme'])): ?>
                      <div class="navbar-item">
                              <p>Current Scheme : <?php echo $_SESSION['scheme']['namescheme'] ?></p>
                      </div>
                  <?php endif; ?>
                  <div class="navbar-item has-drowdown is-hoverable is-boxed">
                      <div class="navbar-link">
                          <a href="/classifier">Classifier</a>
                      </div>
                      <div class="navbar-dropdown">
                          <div class="navbar-item">
                              <a href="/classifier">Job by Job Classifier</a>
                          </div>
                          <div class="navbar-item">
                              Search Classifier
                          </div>
                          <hr class="navbar-divider">
                          <div class="navbar-item">
                              Retag Jobs
                          </div>
                      </div>
                  </div>
                  <div class="navbar-item has-drowdown is-hoverable is-boxed">
                      <div class="navbar-link">
                          <a href="/">Schema/Database</a>
                      </div>
                      <div class="navbar-dropdown">
                          <div class="navbar-item">
                              <a href="/scheme/view">View/Change Schema</a>
                          </div>
                          <div class="navbar-item">
                              <a href="/">New Scheme</a>
                          </div>
                          <hr class="navbar-divider">
                          <div class="navbar-item">
                              <a href="/database">New Jobads Database</a>
                          </div>
                      </div>
                  </div>
                  <div class="navbar-item has-drowdown is-hoverable is-boxed">
                      <div class="navbar-link">
                          <a href="/summary">Summary</a>
                      </div>
                      <div class="navbar-dropdown">
                          <div class="navbar-item">
                              <a href="/summary">Summary</a>
                          </div>
                          <hr class="navbar-divider">
                          <div class="navbar-item">
                              <a href="/summary/jobads">See Tagged Jobads</a>
                          </div>
                      </div>
                  </div>
                  <div class="navbar-item">
                      <a href="/">Home</a>
                  </div>
                  <div class="navbar-item">

                  </div>
              </div>
          </div>
        </nav>
