<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title><?=$title ?></title>
        <link rel="stylesheet" href="http://localhost/css/bulma.min.css">
    </head>

    <body>
        <nav class="navbar" role="navigation" aria-label="main navigation">
          <div class="navbar-menu">
              <div class="navbar-end">
                  <div class="navbar-item has-drowdown is-hoverable is-boxed">
                      <div class="navbar-link">
                          <a href="">Classifier</a>
                      </div>
                      <div class="navbar-dropdown">
                          <div class="navbar-item">
                              <a href="#">Job by Job Classifier</a>
                          </div>
                          <div class="navbar-item">
                              <a href="#">Search Classifier</a>
                          </div>
                          <hr class="navbar-divider">
                          <div class="navbar-item">
                              <a href="#">Retag Jobs</a>
                          </div>
                      </div>
                  </div>
                  <div class="navbar-item has-drowdown is-hoverable is-boxed">
                      <div class="navbar-link">
                          <a href="">Schema</a>
                      </div>
                      <div class="navbar-dropdown">
                          <div class="navbar-item">
                              <a href="#">View Schema</a>
                          </div>
                          <div class="navbar-item">
                              <a href="#">New Schema</a>
                          </div>
                      </div>
                  </div>
                  <div class="navbar-item has-drowdown is-hoverable is-boxed">
                      <div class="navbar-link">
                          <a href="">Summary</a>
                      </div>
                      <div class="navbar-dropdown">
                          <div class="navbar-item">
                              <a href="#">Summary Table</a>
                          </div>
                          <hr class="navbar-divider">
                          <div class="navbar-item">
                              <a href="#">See Tagged Jobads</a>
                          </div>
                      </div>
                  </div>
                  <div class="navbar-item">
                      <a href="/home/">Home</a>
                  </div>
                  <div class="navbar-item">

                  </div>
              </div>
          </div>
        </nav>
