<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title><?=$title ?></title>
        <link rel="stylesheet" href="/css/bulma.min.css">
        <link rel="stylesheet" href="/css/my.css">
    </head>

    <body>
        <nav class="navbar" role="navigation" aria-label="main navigation">
          <div class="navbar-menu">
              <div class="navbar-end">
                  <?php if (isset($_SESSION['schemename'])): ?>
                      <div class="navbar-item">
                              <p>Current Scheme : <?php echo $_SESSION['schemename'] ?></p>
                      </div>
                  <?php endif; ?>
                  <div class="navbar-item has-drowdown is-hoverable is-boxed">
                      <div class="navbar-link">
                          <a href="/classifier">Classifier</a>
                      </div>
                      <div class="navbar-dropdown">
                          <div class="navbar-item">
                              <a href="/classifier">Job by Job Classifier</a>
                          </div>
                          <div class="navbar-item">
                              Search Classifier
                          </div>
                          <hr class="navbar-divider">
                          <div class="navbar-item">
                              Retag Jobs
                          </div>
                      </div>
                  </div>
                  <div class="navbar-item has-drowdown is-hoverable is-boxed">
                      <div class="navbar-link">
                          Schema
                      </div>
                      <div class="navbar-dropdown">
                          <div class="navbar-item">
                              View/Change Schema
                          </div>
                          <div class="navbar-item">
                              <a href="/">New Scheme</a>
                          </div>
                      </div>
                  </div>
                  <div class="navbar-item has-drowdown is-hoverable is-boxed">
                      <div class="navbar-link">
                          <a href="/summary">Summary</a>
                      </div>
                      <div class="navbar-dropdown">
                          <div class="navbar-item">
                              <a href="/summary">Summary</a>
                          </div>
                          <hr class="navbar-divider">
                          <div class="navbar-item">
                              See Tagged Jobads
                          </div>
                      </div>
                  </div>
                  <div class="navbar-item">
                      <a href="/">Home</a>
                  </div>
                  <div class="navbar-item">

                  </div>
              </div>
          </div>
        </nav>
