<body>
    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column">
                    <!-- display data -->
                    <div class="box">
                        <div class="table is-bordered">
                            <table>
                                <thead>

                                </thead>
                                <tbody>
                                    <?php foreach ($_SESSION['jobads'] as $key => $value): ?>
                                        <tr>
                                            <th><?php echo $key ?></th>
                                            <td><?php echo $value ?></td>
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="column">
                    <!-- select category -->
                    <div class="box">
                        <div class="content">
                            <h3>Select Category</h3>
                        </div>
                        <div class="has-text-centered">
                            <?php foreach ($category as $key => $value): ?>
                                <a href="/classifier?categoryname=<?php echo $value['categoryname'] ?>" class="button"><?php echo $value['categoryname']?></a>
                                <br>
                                <br>

                            <?php endforeach; ?>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
