<body>
    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column is-2">

                </div>
                <div class="column">
                    <div class="box">
                        <div class="content has-text-centered">
                            <h3>Done : no more sample left</h3>
                            <br>
                            <hr>
                            <br>
                            <div class="columns">
                                <div class="column">
                                    <a href="/summary/jobads" class="button">View Tagged Jobads / CSV Export</a>
                                </div>
                                <div class="column">
                                    <a href="/summary" class="button">View summary</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="column is-2">

                </div>
            </div>
        </div>
    </section>
</body>
