<body>
    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column">
                    <!-- display data -->
                    <div class="box">
                        <div class="table is-bordered">
                            <table>
                                <thead>

                                </thead>
                                <tbody>
                                    <?php foreach ($_SESSION['jobads'] as $key => $value): ?>
                                        <tr>
                                            <th><?php echo $key ?></th>
                                            <td><?php echo $value ?></td>
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="box has-text-centered">
                        <div class="columns">
                            <div class="column">

                            </div>
                            <div class="column">
                                <div class="table">
                                    <table>
                                        <thead>
                                            <th>no</th>
                                            <th>category</th>
                                            <th>tagcode</th>
                                            <th>tagname</th>
                                            <th>remove</th>
                                        </thead>
                                        <tbody>
                                            <?php
                                                $count = 1;
                                                foreach ($cart as $key => $value) {
                                                    echo "<tr>";
                                                    echo "<td>";
                                                        echo "$count";
                                                    echo "</td>";

                                                    echo "<td>";
                                                        echo($value['namecategory']);
                                                    echo "</td>";

                                                    echo "<td>";
                                                        echo($value['code']);
                                                    echo "</td>";

                                                    echo "<td>";
                                                        echo($value['nametag']);
                                                    echo "</td>";

                                                    echo "<td class='has-text-centered'>";
                                                    echo("<a href='/classifier?action=remove&index=".$key."' class='button is-danger is-outlined'><i class='far fa-trash-alt'></i></a>");
                                                    echo "</td>";

                                                    echo "</tr>";
                                                    $count++;
                                                }
                                            ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="column">

                            </div>
                        </div>
                        <div class="content has-text-centered">
                            <a href="/classifier?action=set " class='button is-success is-borered'>Confirm Tag</a>
                        </div>
                    </div>
                </div>
                <div class="column">
                    <!-- select category -->
                    <div class="box">
                        <div class="content">
                            <h2>Classifier - <?php echo $_GET['categoryname'] ?></h2>
                        </div>
                        <div class="columns">
                            <div class="column has-text-centered">
                                <a href="/classifier" class="button">Back</a>
                            </div>
                            <div class="column has-text-centered">
                                <a href="/classifier?categoryname=<?php echo $_GET['categoryname'] ?>&action=set" class="button">Tag As <?php echo $_GET['categoryname'] ?></a>
                            </div>
                            <div class="column has-text-centered">
                                <a href="/classifier?action=skip" class="button">Skip</a>

                            </div>
                        </div>
                        <div class="columns">
                            <div class="column is-1">

                            </div>
                            <div class="column is-10 has-text-centered">
                                <div class="table">
                                    <table>
                                        <thead>
                                            <th>Code</th>
                                            <th>Tag Name</th>
                                            <th></th>
                                        </thead>
                                        <tbody>
                                            <?php foreach ($tags as $key => $row): ?>
                                                <tr>
                                                    <td><?php echo $row['code'] ?></td>

                                                    <td>
                                                        <div class="tooltip">
                                                            <?php echo $row['nametag'] ?>
                                                            <span class="tooltiptext"><?php echo $row['description']; ?></span>
                                                        </div>
                                                    </td>

                                                    <td>
                                                        <a href="/classifier?categoryname=<?php echo $_GET['categoryname'] ?>&code=<?php echo $row['idtag'] ?>&action=add" class="button is-link is-outlined">
                                                            <i class='far fa-plus-square'></i>
                                                        </a>
                                                    </td>
                                                </tr>
                                            <?php endforeach; ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="column is-1">

                            </div>
                        </div>


                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
