<body>
    <section class="section">
        <div class="container">
            <div class="box">
                <div class="columns">
                    <div class="column">

                    </div>
                    <div class="column has-text-centered">
                        <div class="content">
                            <h3>Success!</h3>
                            <h4>DB name : <?php echo $result['namemasterdb']; ?></h4>
                            <h4>Timestamp : <?php echo $result['timestamp']; ?></h4>
                        </div>
                        <a href="/" class="button is-link">Go Home</a>
                    </div>
                    <div class="column">

                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
