<body>
    <section class="section">
        <div class="container">
            <div class="box">
                <div class="content">
                    <h3>Summary</h3>
                </div>
                <div class="columns">
                    <div class="column is-2">

                    </div>
                    <div class="column is-8">
                        <div class="table">
                            <table>
                                <thead>
                                    <th>Catogory</th>
                                    <?php  $sumarray = [];?>
                                    <?php foreach ($category as $key => $value): ?>
                                        <th><?php echo $value['categoryname'] ?></th>
                                        <?php
                                            $sumarray[$value['categoryname']] = 0;
                                         ?>
                                    <?php endforeach; ?>
                                    <th>Total</th>
                                </thead>
                                <tbody>
                                    <?php foreach ($jobsource as $key => $value): ?>
                                        <?php
                                            $sum = 0;
                                         ?>
                                        <tr>
                                            <th><?php echo $value['jobsourcename'] ?></th>
                                            <?php foreach ($summaryrows[$value['jobsourcename']] as $keyin => $valuein): ?>
                                                <?php
                                                    $sum += $valuein;
                                                    $sumarray[$keyin] += $valuein;
                                                 ?>
                                                <td><?php echo $valuein ?></td>
                                            <?php endforeach; ?>
                                            <td><?php echo $sum ?></td>
                                        </tr>
                                    <?php endforeach; ?>
                                    <tr>
                                        <th>Total</th>
                                    <?php
                                        $grandsum = 0;
                                     ?>
                                    <?php foreach ($sumarray as $key => $value): ?>
                                        <?php $grandsum+=$value ?>
                                        <td><?php echo $value ?></td>
                                    <?php endforeach; ?>
                                        <td><?php echo $grandsum ?></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="column is-2">

                    </div>
                </div>
                <div class="content has-text-centered">
                    <h3>Tagged = <?php echo $grandsum ?>/5000</h3>
                </div>
            </div>
        </div>
    </section>
</body>
