<body>
    <section class="section">
        <div class="container">
            <div class="box">
                <div class="content">
                    <h3>Summary</h3>
                </div>
                <div class="columns">
                    <div class="column is-2">

                    </div>
                    <div class="column is-8">
                        <div class="table">
                            <table>
                                <thead>
                                    <th>category</th>
                                    <th>count</th>
                                </thead>
                                <tbody>
                                    <?php
                                        $total = 0;
                                        foreach ($summaryTable as $key => $value) {
                                            echo "<tr>";
                                            foreach ($value as $keyin => $valuein) {
                                                echo "<td>$valuein</td>";
                                                if ($keyin = 'mycount') {
                                                    $total += (int) $valuein;
                                                }
                                            }
                                            echo "</tr>";
                                        }
                                        echo "<tr><th>Total</th><th>$total</th></tr>";
                                     ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="column is-2">

                    </div>
                </div>
                <div class="content has-text-centered">

                </div>
            </div>
        </div>
    </section>
</body>
